### ISSUE TITLE
System to calculate Contribution Aggregate for "Individual Receipt", "Tribal Receipt", "JF Transfer", and "JF Transfer Memo"

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#472] opened 2022-08-17 16:15 UTC
Business Reason

The Contribution Aggregate field must display the total of the entity's contributions from the calendar year of the report. This is necessary to track contribution limits as well as itemization logic. This amount will be a _rolling total_.

Acceptance Criteria

For the following transactions:

1\. Individual Receipt (Group A)

  2\. Tribal Receipt (Group D)

  3\. Joint Fundraising Transfer (Group E)

  4\. Joint Fundraising PAC Memo (Group F)

CONTRIBUTION AGGREGATE field must meet the following criteria:

*   AMT-12, Required, Read-Only, Currency amount
*   Can be negative
*   Amount Displayed will be the total of contributions that are: 
      *   From the person (ENTITY) 
            *   *   within Aggregation Group of "General"**
    *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
    *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

AND when saving a transaction, any subsequent transactions for the same entity will update. (E.g., if a previous transaction receipt amount is _changed_, it will affect the future aggregations).

DEV NOTES

  For Individual and Tribal Receipt: Refunds from Schedule B will eventually be subtracted in this aggregation (Schedule B, Line 28a)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1087](https://fecgov.atlassian.net/browse/FECFILE-1087)

**Comment by AureliaKhorsand** [comment] 2022-08-17 17:46
Requirements logic: Aggregation is based on the ENTITY (Contact) and chronologically based on date of transaction (contribution date). If contribution date is the same, default to the time that the transaction was created.

**Comment by WiseQA** [comment] 2022-10-14 11:32
Per email from Mitchell this ticket for this sprint devs have tasked Elaine to write an e2e test for 472 this sprint to help test it.   Mitchell will make sure Todd has QA notes in the ticket for future Adhoc testing.   There will not be a QA test on this ticket this sprint.

@Elaine-Krauss-TCG as we have done in the past with e2e tickets please put in QA bucket and we will review.  Thanks

**Comment by AureliaKhorsand** [comment] 2022-10-17 14:46
@toddlees Contribution Aggregate not updating between transactions. Sending back to In Progress

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/9c376258-e003-4fb9-b54a-b5b438625b27)

Transaction with 7/10/1999 date should read $299, but also reads $150.
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/13c5cdca-fce3-4d39-aaf5-bc0ebd0594c0)

**Comment by mjtravers** [comment] 2022-10-17 16:11
Fixes to calculation of contribution aggregation put in for the display in the transaction from. Sending to CR

**Comment by mjtravers** [comment] 2022-10-17 16:19
Passed CR by @toddlees . Sending back to QA

**Comment by AureliaKhorsand** [comment] 2022-10-17 16:53
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/2506491f-695e-474f-9180-ae99c7b3efd1)

**Comment by WiseQA** [comment] 2022-10-17 21:10
QA review is based on BA testing.   Ticket per BA passes as intended.   e2e testing will be verified again by QA in ticket #617 assigned to Sprint 16.

QA review based on above statement.  Moved to Stage Ready.

**Closed as completed** 2022-10-27 15:48 UTC
