### ISSUE TITLE
UI: Landing Page: Fix Sign up buttons

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1963] opened 2024-05-22 15:22 UTC
Business Reason
The sign up buttons should work

 Task
- [ ] Link "SIGN UP" header nav link to https://idp.int.identitysandbox.gov/sign_up/enter_email
- [ ] Link "Sign up with Login.gov" button to https://idp.int.identitysandbox.gov/sign_up/enter_email

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
  Wireframe
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/67e7bc26-71a8-4789-95d6-65ca28ecb206)

### Design ### 
 null

**Comment by MitchellTCG** [comment] 2024-05-22 15:22
@GreggMoreland pls review

**Comment by AureliaKhorsand** [comment] 2024-05-22 16:57
Duplicate of #1683. Closing.

**Closed as completed by AureliaKhorsand** 2024-05-22 16:57 UTC
Labels: OBE
