### ISSUE TITLE
Web app authentication technical review

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#36] opened 2022-01-04 19:49 UTC
Review and document existing authentication and session management for fecfile-online web app. Investigate Login.gov and create a strategy for integrating the service into the web app as its authentication service.

**Acceptance Criteria:**
- [ ] Documentation describing existing authentication and session management, linked here
- [ ] Documentation on integration of Login.gov service, linked here
- [ ] Development ticket created for integration, linked here

Note: This is a research/spike ticket. No coding.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment] 2022-01-12 16:20
Duplicate of #42; moving to OBE

**Comment by AureliaKhorsand** [comment] 2022-01-12 18:35
Refinement Discussion: Contract phrases it as "**Consider** using Login.gov as a secure sign in service for FECFile Online". Researching alternatives to login.gov is not in the scope of this ticket.

Moving back to AA, more clarification on deliverables needed. Will break if out into 1) figuring out how authentication works, 2) looking into third party services

**Comment by AureliaKhorsand** [comment] 2022-03-15 17:52
Duplicate of [web-app #42](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/42)

**Closed as completed by AureliaKhorsand** 2022-03-15 17:52 UTC
Labels: OBE
