### ISSUE TITLE
System to hide 'Restore deleted contacts' button if there are no deleted contacts

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1814] opened 2024-03-25 15:32 UTC
Business Reason

As a user, I will not be able to see the 'Restore deleted contacts' button on the Manage Contacts page if I do not have any deleted contacts to recorver so that I can see what actions are available

Acceptance Criteria

***Given*** user on Manage Contacts page

  ***When*** there are no Contacts to be recovered

  ***Then*** user will not see the 'Restore deleted contacts' button

### QA Notes ###
 
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  Wireframe
![Image](https://github.com/fecgov/fecfile-web-app/assets/100313668/901d7929-0e0b-490a-8ecb-119048f4631b)

### Design ###
 
 null

 See full ticket and images here: [FECFILE-453](https://fecgov.atlassian.net/browse/FECFILE-453)

**Comment by AureliaKhorsand** [comment] 2024-04-29 17:05
This is a duplicate of #1815 . Closing as OBE.

**Comment by AureliaKhorsand** [comment] 2024-04-29 17:06
Disregard the closure. I can't read.

**Comment by mary-tcg** [comment] 2024-05-07 17:37
@MitchellTCG @AureliaKhorsand wireframe added

**Comment by sasha-dresden** [comment] 2024-05-10 18:56
Passes code review. Leaving a note here that we might want to make an api endpoint that just checks whether or not there are any deleted contacts. Currently this uses the list end point and checks the count on the front end which works fine and was quite snappy on my local. But if it proves sluggish with load, that could be an easy point of optimization.

**Comment by WiseQA** [comment] 2024-05-14 15:26
QA review verified when there are no deleted contacts for my committee the "Restore deleted contacts" button is not displayed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/714b1b24-dc57-4bb3-82a9-1ca007763449)

QA Review Completed.   Moved to Stage Ready.

**Closed as completed** 2024-05-28 14:51 UTC
